local ampOnIcon = [[ASCII:
.....1a..........AC..........E
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
.....5c.......................
]]

local ampOffIcon = [[ASCII:
.....1a.....x....AC.y.......zE
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
...x.5c....y.......z..........
]]

local amphetamine = hs.menubar.new()

local function setAmphetamineDisplay(state)
    if state then
        amphetamine:setIcon(ampOnIcon)
    else
        amphetamine:setIcon(ampOffIcon)
    end
end

local function amphetamineClicked()
    setAmphetamineDisplay(hs.caffeinate.toggle("displayIdle"))
end

local obj = {}

function obj:init()
  if amphetamine then
      amphetamine:setClickCallback(amphetamineClicked)
      setAmphetamineDisplay(hs.caffeinate.get("displayIdle"))
  end
end

return obj
